### ISSUE TITLE
Unable to install the app

### ISSUE THREAD

**Issue by adrienlacombe** [YunoHost-Apps/lxd_ynh#10]
### Describe the bug

I can't install LXD from CLI or web UI, error message displayed in web is: argument @args: expected one argument

### Context

- Hardware: Intel NUC at home
- YunoHost version: 4.2.6.1 (stable)
- I have access to my server: through SSH and/or through the webadmin and/or direct access via keyboard / screen; I report the bug from webadmin only.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: this repo app

### Steps to reproduce

from the CLI: sudo yunohost app install lxd

from the webadmin: error message displayed is 'argument @args: expected one argument'

### Expected behavior

LXD installs nicely

### Logs

![image](https://user-images.githubusercontent.com/6303520/124093190-e7bf0e80-da57-11eb-8fd5-335dea9c1018.png)

**Comment by tituspijean** [comment]
This is an upstream issue from the webadmin. I have created a relevant issue about it. 😉

**Comment by adrienlacombe** [comment]
Thank you @tituspijean! Could you please share a link to the issue so I can subscribe to notifications? Thank you :)

**Comment by tituspijean** [comment]
Hum, it is linked right above my last comment, but OK: https://github.com/YunoHost/issues/issues/1832

**Comment by adrienlacombe** [comment]
Jeez, sorry, I was blind!

**Comment by adrienlacombe** [comment]
Hi @tituspijean it doesn't seem to work from CLI, do you want a new issue?
https://paste.yunohost.org/raw/oxagicaxiy

Thank you!

**Comment by tituspijean** [comment]
You should indeed open a new issue, as your new problem with dependencies is another matter.

**Comment by adrienlacombe** [comment]
No problem, will do :) thank you!
What I am trying to achieve with this app is to have VMs along side Yunohost (that is running directly on the server). Is this what this app would do?

**Comment by tituspijean** [comment]
Yup, it should help you with that. (*If it were willing to be installed* 😛 )

**Comment by tituspijean** [comment]
Closing here, since the upstream issue has been resolved.
