### ISSUE TITLE
Unable to install lxd app from CLI

### ISSUE THREAD

**Issue by adrienlacombe** [YunoHost-Apps/lxd_ynh#11]
### Describe the bug

`sudo yunohost app install lxd` fails to complete successfully

### Context

- Hardware: *Intel NUC at home*
- YunoHost version: 4.2.6.1 (stable)
- I have access to my server: *through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: this repo app

### Steps to reproduce

`sudo yunohost app install lxd`

### Expected behavior

Sucess

### Logs

https://paste.yunohost.org/raw/oxagicaxiy

**Comment by tituspijean** [comment]
```
2021-07-12 14:08:31,747: DEBUG - The following packages will be REMOVED:
2021-07-12 14:08:31,748: DEBUG -   busybox
[...]
2021-07-12 14:08:31,757: DEBUG - 0 upgraded, 30 newly installed, 1 to remove and 0 not upgraded.
2021-07-12 14:08:31,757: DEBUG - E: Packages need to be removed but remove is disabled.
```

Can you try `apt-get remove busybox` before trying to install again, if you think this package is not needed by another software on your server?

**Comment by adrienlacombe** [comment]
Is there a way I can make sure it won't harm my yunohost? thank you @tituspijean!

**Comment by adrienlacombe** [comment]
I think a lot of packages depends on busybox unfortunately...

**Comment by adrienlacombe** [comment]
`sudo apt-get install busybox-static` installs busybox-static and removes busybox. It seems to work.
