### ISSUE TITLE
Error installing LXD

### ISSUE THREAD

**Issue by collector-ynh** [YunoHost-Apps/lxd_ynh#35]
The LXD application does not install, here are the logs: https://paste.yunohost.org/raw/sevuzifoso

Is it that there is a solution to solve the problem?

**Comment by kay0u** [comment]
Are you using busybox? I'm not sure what's going on, but it seems that this package makes LXD uninstallable.

If not, could you try to run

```
sudo apt autoremove busybox --dry-run
```
And give me the log of this command.

**Comment by collector-ynh** [comment]
Hello, here is the line return of the command `sudo apt autoremove busybox --dry-run` : https://termbin.com/7fdo

```
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  busybox-static
The following packages will be REMOVED:
  busybox cryptsetup cryptsetup-bin cryptsetup-initramfs
The following NEW packages will be installed:
  busybox-static
0 upgraded, 1 newly installed, 4 to remove and 0 not upgraded.
Remv cryptsetup-initramfs [2:2.3.7-1+deb11u1]
Remv busybox [1:1.30.1-6+b3]
Remv cryptsetup [2:2.3.7-1+deb11u1]
Remv cryptsetup-bin [2:2.3.7-1+deb11u1]
Inst busybox-static (1:1.30.1-6+b3 Debian:11.3/stable [amd64])
Conf busybox-static (1:1.30.1-6+b3 Debian:11.3/stable [amd64])
```

**Comment by hobhobuk** [comment]
Hey,
I think I may be having a similar issue.  
Running on a intel NUC, although I did have to install debian minimal first then yunohost due to boot issues..
Unsure if this is why?

Log: https://paste.yunohost.org/raw/rozinokoxi

Can I use the busybox fix or would that mess it up?

**Comment by ChvckN0rri5** [comment]
I am having the same issue. It would be redundant to post the logs at this point, but here they are:
[LOG](https://paste.yunohost.org/raw/jezuducayu)


In the meantime, this is after a manual install of dependencies:
```
The following packages have unmet dependencies:
 busybox : Conflicts: busybox-static but 1:1.30.1-4 is to be installed
 busybox-static : Conflicts: busybox
E: Unable to correct problems, you have held broken packages.
```

I have ran dpkg --configure -a with no output generated, confirming that that there are no held broken packages. So I guess I need to know what to do with busy box...

Please advise. 

Thank you
ChvckN0rri5

**Comment by thibaut62** [comment]
hello i have a corrupt source when installing :
https://paste.yunohost.org/raw/elibanifev

**Comment by Tagadda** [comment]
I'm trying to install lxd on a frech YunoHost stable in a VM.
A huge apt mess ?
https://paste.yunohost.org/raw/jirafatuke

**Comment by yalh76** [comment]
> I'm trying to install lxd on a frech YunoHost stable in a VM. A huge apt mess ? https://paste.yunohost.org/raw/jirafatuke

Yes, you should remove `busybox` before

**Comment by moortaube** [comment]
I got a similar error on installing: https://paste.yunohost.org/raw/malucumibe

And removing `busybox` with `sudo apt autoremove busybox` fixed it for me, too.
